name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "computational_paths"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.24.0"
