name = "computational_paths"
version = "0.1.0"
defaultTargets = ["computational_paths"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.24.0"

[[lean_lib]]
name = "ComputationalPaths"
roots = [
  "ComputationalPaths",
  "Kan",
  "Equivalence",
  "Operad",
  "Topos",
  "Motivic",
  "MotivicCohomology",
  "Chromatic",
  "Condensed",
  "Categorification",
  "Cluster",
  "VertexAlgebra",
  "Descent",
  "Etale",
  "Crystalline",
  "Deformation",
  "DerivedCategories",
  "Moduli",
  "Cobordism",
  "TFT",
  "Arithmetic",
  "Langlands",
  "GeometricSatake",
  "Anabelian",
  "Birational",
  "Simplicial",
  "InfinityCategory",
  "Factorization",
  "Perfectoid",
  "PerfectoidCohomology",
  "Padic",
  "Prismatic",
  "Tropical",
  "Hodge",
  "Log",
  "RepStability",
  "HomologicalStability",
  "SpectralSequence",
  "Intersection",
  "GRT",
  "GIT",
  "DAG",
  "Quantum",
  "KacMoody",
  "Mirror",
  "SymplecticDuality",
  "Floer",
  "NCG",
  "OperadicAlgebra",
]

[[lean_exe]]
name = "computational_paths"
root = "Main"
